added feeder subsystem
HighlanderRobotics/Crescendo pull request #34
Opened 2024-02-04 00:06 UTC by Lewis-Seiden

2024-02-04 22:28 UTC, Awesomeplayer165 requested changes
small things

2024-02-04 22:28 UTC, Awesomeplayer165 commented on src/main/java/frc/robot/subsystems/feeder/FeederSubsystem.java
> +  /** Creates a new FeederSubsystem. */
odd javadocs across all of these RPs?

2024-02-04 22:28 UTC, Awesomeplayer165 commented on src/main/java/frc/robot/subsystems/feeder/FeederIOReal.java
> +/** Add your docs here. */
javadocs?

2024-02-04 22:52 UTC, Lewis-Seiden commented on src/main/java/frc/robot/subsystems/feeder/FeederSubsystem.java
> +  /** Creates a new FeederSubsystem. */
wpilib vscode autogenerates these

2024-02-05 17:55 UTC, Awesomeplayer165 requested changes
super duper small things.

2024-02-05 17:55 UTC, Awesomeplayer165 commented on src/main/java/frc/robot/subsystems/feeder/FeederIO.java
> +public interface FeederIO {
does this deliberately not have a comment?
sorry if I was not thorough enough, but suggestions last time were only duplicates wrt the whole PR.

2024-02-05 17:56 UTC, Awesomeplayer165 commented on src/main/java/frc/robot/subsystems/feeder/FeederIO.java
> +public interface FeederIO {
looking through the other PRs, you have deliberately removed these comments. OK, just making sure we are consistent.

2024-02-05 17:56 UTC, Awesomeplayer165 approved these changes
LGTM

2024-02-06 00:17 UTC, merged