Leds
HighlanderRobotics/Crescendo pull request #46
Opened 2024-02-17 21:48 UTC by Lewis-Seiden

2024-02-17 23:16 UTC, Awesomeplayer165 requested changes
General consistency stuff.

2024-02-17 23:16 UTC, Awesomeplayer165 commented on src/main/java/frc/robot/subsystems/leds/LEDIOSim.java
> +// ledioreal
```suggestion
// LEDIOReal
```

2024-02-17 23:16 UTC, Awesomeplayer165 commented on src/main/java/frc/robot/subsystems/leds/LEDIOSim.java
> +    led.setLength(buffer.getLength());
Line break

2024-02-17 23:16 UTC, Awesomeplayer165 commented on src/main/java/frc/robot/subsystems/leds/LEDSubsystem.java
> +  double dashStart = 0;
Should any of these be `private`?

2024-02-17 23:16 UTC, Awesomeplayer165 commented on src/main/java/frc/robot/subsystems/leds/LEDSubsystem.java
> +  public Command defaultStateDisplay(BooleanSupplier enabled, BooleanSupplier targetIsSpeaker) {
Postfix Cmd?

2024-02-17 23:16 UTC, Awesomeplayer165 commented on src/main/java/frc/robot/subsystems/leds/LEDIOSim.java
> +  AddressableLEDBuffer buffer;
Private or public?

2024-02-17 23:16 UTC, Awesomeplayer165 commented on src/main/java/frc/robot/subsystems/leds/LEDIOReal.java
> +  AddressableLEDBuffer buffer;
Public or private?

2024-02-17 23:28 UTC, Lewis-Seiden commented on src/main/java/frc/robot/subsystems/leds/LEDIOSim.java
> +    led.setLength(buffer.getLength());
?

2024-02-18 04:09 UTC, Awesomeplayer165 requested changes
general small things I didn't see earlier.

2024-02-18 04:09 UTC, Awesomeplayer165 commented on src/main/java/frc/robot/subsystems/leds/LEDIOSim.java
> +    led.setLength(buffer.getLength());
group similar ideas together for consistency with rest of codebase.

```suggestion
    buffer = new AddressableLEDBuffer(LEDSubsystem.LED_LENGTH);
    
    led.setLength(buffer.getLength());
```

2024-02-18 04:09 UTC, Awesomeplayer165 commented on src/main/java/frc/robot/subsystems/leds/LEDSubsystem.java
> +              setIndex(i, Color.kBlack);
```suggestion
              setIndex(i, i < progress.getAsDouble() * LED_LENGTH ? color : Color.kBlack);
```

2024-02-18 04:09 UTC, Awesomeplayer165 commented on src/main/java/frc/robot/subsystems/leds/LEDSubsystem.java
> +  private double dashStart = 0;
add comments as to what time units or meaning start has?

2024-02-20 06:27 UTC, Awesomeplayer165 approved these changes

2024-02-20 06:27 UTC, merged